databases:
  - name: budget_builder
    databaseName: budget_builder_production
    user: budget_builder_production_user

services:
  - type: web
    name: budgetbuilder
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_builder_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false